sonarr:
  service:
    main:
      ports:
        http:
          port: 8989
  persistence:
    media:
       enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media
    downloads:
       enabled: true
       mountPath: /downloads
       type: pvc
       existingClaim: downloads
    config:
       enabled: true
       type: pvc
       existingClaim: config-sonarr