sonarr:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8989
          targetPort: 8989
          nodePort: 30003
  persistence:
    config:
       enabled: true
       mountPath: /config
       storageClass: volume-hostpath
       accessMode: ReadWriteOnce
       size: 1Gi
    media:
       enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media