mautrix-meta:
  image:
    repository: dock.mau.dev/mautrix/meta
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  service:
    main:
      enabled: true
      http:
          port: 29319
  persistence:
    config:
      existingClaim: mautrix-meta-data