authentik:
  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "ThisIsNotASecurePassword"
    log_level: trace
  ingress:
      # Specify kubernetes ingress controller class name
      ingressClassName: nginx
      enabled: true
      hosts:
          # Specify external host name
          - host: authentik.azaurus.dev
            paths:
                - path: "/"
                  pathType: Prefix

  postgresql:
      enabled: true
      postgresqlPassword: "ThisIsNotASecurePassword"
  redis:
      enabled: true