headscale:
  env:
    HEADSCALE_DNS_CONFIG_BASE_DOMAIN: azaurus.dev
    HEADSCALE_SERVER_URL: headscale.azaurus.dev

  sidecars:
    ui:
      image: ghcr.io/gurucomputing/headscale-ui:latest
      ports:
        - name: http
          containerPort: 80

  service:
    main:
      ports:
        ui:
          port: 80
        http:
          port: 8080
        metrics:
          port: 9090
        grpc:
          enabled: false
          port: 50443
