shelf:
  image:
    repository: ghcr.io/shelf-nu/shelf.nu
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  service:
    main:
      enabled: true
      http:
          port: 8080