jellyfin:
   service:
    main:
      type: NodePort
      ports:
        http:
          port: 8096
          targetPort: 8096
          nodePort: 30000
   persistence:
     media:
       enabled: true
       mountPath: /media
       storageClass: volume-hostpath
     cache:
       enabled: true
       mountPath: /cache
       existingClaim: jellyfin-cache
     config:
       enabled: true
       mountPath: /config
       existingClaim: jellyfin-config
