jellyfin:
   service:
    main:
      type: NodePort
      ports:
        http:
          port: 8096
          targetPort: 8096
          nodePort: 30000
   persistence:
     media:
       enabled: true
       mountPath: /media
       existingClaim: pvc-d22aa8bf-4018-4c40-998d-3ad80e9510be
     cache:
       enabled: true
       mountPath: /cache
       existingClaim: pvc-1dd5e60a-b218-4092-8ab5-e1c1e8ab6896
     config:
       enabled: true
       mountPath: /config
       existingClaim: pvc-efa5c032-9f03-4bcd-8fb1-1b0f7a140d6c
