jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host jellyfin.local
          paths:
            - path: /
              pathType: Prefix