jellyfin:
   service:
    main:
      type: NodePort
      ports:
        http:
          port: 8096
          targetPort: 8096
          nodePort: 30000
   persistence:
     media:
       enabled: true
       mountPath: /media
       existingClaim: pvc-ff18c8a9-f11c-4bd7-8ef8-7c99e50d7550
       subPath: media
     #cache:
     #  enabled: true
     #  mountPath: /cache
     #  storageClass: volume-hostpath
     #  accessMode: ReadWriteOnce
     #  size: 1Gi
     #config:
     #  enabled: true
     #  mountPath: /config
     #  storageClass: volume-hostpath
     #  accessMode: ReadWriteOnce
     #  size: 1Gi
