jellyfin:
   service:
    main:
      type: NodePort
      ports:
        http:
          port: 8096
          targetPort: 8096
          nodePort: 30000
   persistence:
     media:
       enabled: true
       mountPath: /media
       existingClaim: pvc-d22aa8bf-4018-4c40-998d-3ad80e9510be
     cache:
       enabled: true
       mountPath: /cache
       existingClaim: default/jellyfin-cache
     config:
       enabled: true
       mountPath: /config
       existingClaim: default/jellyfin-config
