jellyfin:
  ingress:
    enabled: true
    ingressClassName: nginx
    rules:
    - host: myservicea.foo.org
    http:
      paths:
      - path: /
        backend:
          serviceName: myservicea
          servicePort: 80