jellyfin:
   service:
    main:
      type: NodePort
      ports:
        http:
          port: 8096
          targetPort: 8096
          nodePort: 30000
   persistence:
     media:
       enabled: true
       type: pvc
       mountPath: /media
       storageClass: volume-hostpath
       accessMode: ReadWriteOnce
       size: 1Gi
     cache:
       enabled: true
       type: pvc
       mountPath: /cache
       storageClass: volume-hostpath
       accessMode: ReadWriteOnce
       size: 1Gi
