tunnel: [tunnel_uuid]
credentials-file: /root/.cloudflared/[tunnel_uuid].json

ingress:
  - hostname: emby.azaurus.dev
    service: http://localhost:30000
  - hostname: sonarr.azaurus.dev
    service: http://localhost:30003
  - hostname: radarr.azaurus.dev
    service: http://localhost:30002
  - hostname: qbittorrent.azaurus.dev
    service: http://localhost:30001
  - hostname: jackett.azaurus.dev
    service: http://localhost:30006
  - hostname: matrix.azaurus.dev
    service: http://localhost:30009
  - hostname: heimdall.azaurus.dev
    service: http://localhost:30004
  - hostname: ombi.azaurus.dev
    service: http://localhost:30011
  - hostname: vikunja.azaurus.dev
    service: http://localhost:30012
  - service: http_status:404


