cloudflared:
  tunnelID: "f711274a-e21a-4d8a-85e6-b6492dc059be"
  auth:
    accountTag: "0cc2af205c8980e76b19852b3183bcfd"
    tunnelName: "homelab"
    tunnelSecret: "UPDATE IN KUBERNETES"
  ingress:
    - hostname: sonarr.azaurus.dev
      service: http://sonarr.default.svc.cluster.local:8989 # this should be the correct dns and port for your service
    - hostname: radarr.azaurus.dev
      service: http://radarr.default.svc.cluster.local:7878 # this should be the correct dns and port for your service
    - hostname: emby.azaurus.dev
      service: http://emby.default.svc.cluster.local:8096 # this should be the correct dns and port for your service
    - hostname: qbittorrent.azaurus.dev
      service: http://qbittorrent.default.svc.cluster.local:8080 # this should be the correct dns and port for your service
    - hostname: ombi.azaurus.dev
      service: http://ombi.default.svc.cluster.local:3579 # this should be the correct dns and port for your service
    - hostname: jackett.azaurus.dev
      service: http://jackett.default.svc.cluster.local:9117 # this should be the correct dns and port for your service
    - hostname: element.azaurus.dev
      service: http://element-web.default.svc.cluster.local:80 # this should be the correct dns and port for your service
    - hostname: matrix.azaurus.dev
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local    
    - hostname: jellyfin.azaurus.dev
      service: http://jellyfin.default.svc.cluster.local:8096 # this should be the correct dns and port for your service
    - hostname: uptime.azaurus.dev
      service: http://uptime-kuma.default.svc.cluster.local:3001 # this should be the correct dns and port for your service
    - hostname: heimdall.azaurus.dev
      service: http://heimdall.default.svc.cluster.local:80 # this should be the correct dns and port for your service
    - hostname: gotify.azaurus.dev
      service: http://gotify.default.svc.cluster.local:80 # this should be the correct dns and port for your service
    - hostname: bazarr.azaurus.dev
      service: http://bazarr.default.svc.cluster.local:6767 # this should be the correct dns and port for your service
    - hostname: chartmuseum.azaurus.dev
      service: http://chartmuseum.default.svc.cluster.local:8080 # this should be the correct dns and port for your service
    - hostname: nzbget.azaurus.dev
      service: http://nzbget.default.svc.cluster.local:6789 # this should be the correct dns and port for your service
    - hostname: grafana.azaurus.dev
      service: http://grafana.default.svc.cluster.local:80 # this should be the correct dns and port for your service  
    - hostname: nextcloud.azaurus.dev
      service: http://nextcloud.default.svc.cluster.local:8080 # this should be the correct dns and port for your service
    - hostname: blog.azaurus.dev
      service: http://ghost.default.svc.cluster.local:443 # this should be the correct dns and port for your service
    - hostname: readarr.azaurus.dev
      service: http://readarr.default.svc.cluster.local:8787 # this should be the correct dns and port for your service
    - hostname: kavita.azaurus.dev
      service: http://kavita.default.svc.cluster.local:10189 # this should be the correct dns and port for your service
    - hostname: prowlarr.azaurus.dev
      service: http://prowlarr.default.svc.cluster.local:9696 # this should be the correct dns and port for your service
    - hostname: ment-vault.azaurus.dev
      service: http://ment-vault-wikijs.default.svc.cluster.local:10045 # this should be the correct dns and port for your service
    - hostname: calibre-web.azaurus.dev
      service: http://calibre-web.default.svc.cluster.local:8083 # this should be the correct dns and port for your service
    - hostname: calibre.azaurus.dev
      service: http://calibre.default.svc.cluster.local:8084 # this should be the correct dns and port for your service
    # - hostname: prometheus.azaurus.dev
    #   service: http://prometheus-server.default.svc.cluster.local:80 # this should be the correct dns and port for your service
    - service: http_status:404