ntfy:
  service:
    main:
      ports:
        http:
          port: 80

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    cache:
      enabled: true
      mountPath: /var/cache/ntfy
      accessMode: ReadWriteOnce
      size: 5Gi
    config:
      enabled: true
      mountPath: /etc/ntfy
      accessMode: ReadWriteOnce
      size: 5Gi