grafana:
  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 3000
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: "grafana-admin"
    userKey: admin-user
    passwordKey: admin-password