{{- range $index, $stack := .Values.stacks }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $stack.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ $.Values.spec.source.repoURL }}
        revision: {{ $.Values.spec.source.targetRevision }}
        directories:
          - path: homelab/{{ $stack.name }}/*
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ default `{{path.basename}}` $stack.namespace }}'
      project: default # TODO
      source:
        repoURL: {{ $.Values.spec.source.repoURL }}
        path: '{{ `{{path}}` }}'
        targetRevision: {{ $.Values.spec.source.targetRevision }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
{{- end }}
