---
# For setting microk8s homepath storage path
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: volume-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/volume
volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: volume-hostpath
  #volumeName: jellyfin-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: volume-hostpath
  #volumeName: jellyfin-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: volume-hostpath
  #volumeName: jellyfin-media