---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-volume-media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 1Gi #1Gi
  storageClassName: volume-hostpath
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-volume-cache
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 1Gi #1Gi
  storageClassName: volume-hostpath
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-volume-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 1Gi #1Gi
  storageClassName: volume-hostpath
