---
# For setting microk8s homepath storage path
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: volume-hostpath
#provisioner: microk8s.io/hostpath
#reclaimPolicy: Delete
#parameters:
#  pvDir: /mnt/volume
#volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: nfs-client
  #volumeName: jellyfin-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: nfs-client
  #volumeName: jellyfin-media
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-ombi
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 3Gi #1Gi
  storageClassName: nfs-client
  #volumeName: jellyfin-media 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-jellyfin
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 3Gi #1Gi
  storageClassName: nfs-client
  #volumeName: jellyfin-media   
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 300Gi #1Gi
  storageClassName: nfs-client
  #volumeName: jellyfin-media   
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-content
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 15Gi #1Gi
  storageClassName: nfs-client 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: books
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 15Gi #1Gi
  storageClassName: nfs-client 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre-db
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 10Gi #1Gi
  storageClassName: nfs-client 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-db
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 400Gi #1Gi
  storageClassName: nfs-client 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-prowlarr
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany" #"ReadWriteMany"
  resources:
    requests:
      storage: 4Gi #1Gi
  storageClassName: nfs-client 
---