radarr:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 7878
          targetPort: 7878
          nodePort: 30002
  persistence:
    media:
       enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media
    downloads:
       enabled: true
       mountPath: /downloads
       type: pvc
       existingClaim: downloads
    #config:
    #   enabled: true
    #   type: pvc
    #   existingClaim: config-radarr
      