radarr:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 7878
          targetPort: 7878
          nodePort: 30002
  persistence:
    media:
       enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media
      