radarr:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 7878
          targetPort: 7878
          nodePort: 30002
  persistence:
    config:
       enabled: true
       mountPath: /config
       storageClass: volume-hostpath
       accessMode: ReadWriteOnce
       size: 1Gi
    media:
       enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media
      