calibre-web:
  service:
    main:
      ports:
        http:
          port: 8083
  persistence:
    config:
      enabled: true
      mountPath: /config
    books:
       enabled: true
       mountPath: /books
       type: pvc
       existingClaim: books
    db:
      enabled: true
      mountPath: /db
      type: pvc
      existingClaim: calibre-db
