element-web:
  service:
    type: NodePort
    nodePort: 30008
    port: 80
  configjson:
    default_server_config:
      m.homeserver:
        base_url: "http://pranj.io"
        server_name: "pranj.io"
