element-web:
  service:
    type: NodePort
    nodePort: 30008
    port: 80
  configjson:
    default_server_config:
      m.homeserver:
        base_url: "https://matrix.azaurus.dev"
        server_name: "matrix.azaurus.dev"
