element-web:
  service:
    type: NodePort
    ports:
    - name: http
      nodePort: 30008
      port: 80
      protocol: TCP
      targetPort: http
  configjson:
    m.homeserver:
      base_url: "http://pranj.io"
      server_name: "pranj.io"
