nextcloud:
  service:
    type: ClusterIP
    port: 8080
  nextcloud:
    host: nextcloud.azaurus.dev
    ## Use an existing secret
    existingSecret:
      enabled: true
      secretName: nextcloud-account
      usernameKey: username
      passwordKey: password
      # tokenKey: serverinfo_token
      # smtpUsernameKey: smtp_username
      # smtpPasswordKey: smtp_password
  internalDatabase:
    enabled: false
    name: nextcloud
  persistence:
    # Nextcloud Data (/var/www/html)
    enabled: true
    type: pvc
    existingClaim: nextcloud-data
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
    
  mariadb:
    ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
    enabled: true

    auth:
      database: nextcloud
      username: nextcloud
      password: changeme
    architecture: standalone
    persistence:
      enabled: true
      type: pvc
      existingClaim: nextcloud-db
  
  redis:
    enabled: false
    auth:
      enabled: true
      password: 'changeme'