vikunja:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8080
          targetPort: 8080
          nodePort: 30012
  persistence:
    files:
      enabled: true
      existingClaim: files-vikunja