jellyfin:
  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: config-jellyfin
    media:
      enabled: true
      existingClaim: media
      mountPath: /media
    cache:
      enabled: true
      mountPath: "/cache"
      type: "emptyDir"
    transcode:
      enabled: true
      mountPath: "/config/transcodes"
      type: "emptyDir"
