jellyfin:
  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: config-jellyfin
    media:
      enabled: true
      existingClaim: media
      mountPath: /media
    cache:
      enabled: true
    transcode:
      enabled: false
