
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent
---
apiVersion: v1
kind: Namespace
metadata:
  name: radarr
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
---
apiVersion: v1
kind: Namespace
metadata:
  name: dashy