apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: qbittorrent
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: qbittorrent
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/qBittorrent
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}