speedtest:
  service:
    main:
      ports:
        main:
          enabled: true
          protocol: tcp
          port: 9798

  metrics:
    main:
      enabled: true
      type: "servicemonitor"
      endpoints:
        - port: main
          path: /metrics
          interval: 1h
      prometheusRule:
        enabled: false

  portal:
    open:
      enabled: false
  securityContext:
    container:
      readOnlyRootFilesystem: false
