speedtest-exporter:
  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          enabled: false
        metrics:
          enabled: true
          protocol: TCP
          port: 9798

  metrics:
    enabled: true
    serviceMonitor:
      interval: 60m
      scrapeTimeout: 1m
      labels: {}