readarr:
  service:
    main:
      ports:
        http:
          port: 8787
  persistence:
    books:
       enabled: true
       mountPath: /books
       type: pvc
       existingClaim: books
    downloads:
       enabled: true
       mountPath: /downloads
       type: pvc
       existingClaim: downloads
    config:
       enabled: true
  probes:
    liveness:
      enabled: false
      ## Set this to true if you wish to specify your own livenessProbe
      custom: false
      ## The spec field contains the values for the default livenessProbe.
      ## If you selected custom: true, this field holds the definition of the livenessProbe.
      spec:
        exec:
          command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:8787/api/v1/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
        failureThreshold: 5
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10

  portal:
    enabled: true
