privatebin:
  service:
    main:
      ports:
        http:
          port: 8080
  persistence:
    data:
      enabled: false
      mountPath: /srv/data
      accessMode: ReadWriteOnce
      size: 2Gi