privatebin:
  service:
    main:
      ports:
        http:
          port: 8080
  persistence:
    data:
      enabled: false
      mountPath: /srv/data
      accessMode: ReadWriteOnce
      size: 2Gi
  config:
    main:
      name: "PrivateBin"
    expire:
      default: "1week"
    expire_options:
      5min: 300
      10min: 600
      1hour: 3600
      1day: 86400
      1week: 604800
      1month: 2592000
      1year: 31536000
      never: 0
    formatter_options:
      plaintext: "Plain Text"
      syntaxhighlighting: "Source Code"
      markdown: "Markdown"
    traffic:
      limit: 10
      # exemptedIp: "1.2.3.4,10.10.10/24"