cops:
  service:
    main:
      ports:
        main:
          port: 80
          protocol: HTTP
          targetPort: 80

  persistence:
    config:
      enabled: true
      mountPath: /config
    books:
      enabled: true
      mountPath: /books
      type: pvc
      existingClaim: calibre-db

  portal:
    enabled: true
