bazarr:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 6767
          targetPort: 6767
          nodePort: 30017
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 2Gi