qbittorrent:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8080
          nodePort: 30001
          targetPort: 8080
    bittorrent:
      enabled: true
      type: NodePort
      ports:
        bittorrent:
          enabled: true
          port: 6881
          protocol: TCP
          targetPort: 6881
          nodePort: 30010
  persistence:
    media:
      enabled: true
      type: pvc
      mountPath: /media
      existingClaim: media
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads