qbittorrent:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8080
          nodePort: 30001
          targetPort: 8080
    bittorrent:
      enabled: true
      type: NodePort
      ports:
        bittorrent:
          enabled: true
          port: 6881
          protocol: TCP
          targetPort: 6881
          nodePort: 30010
  persistence:
    media:
      enabled: true
      type: pvc
      mountPath: /media
      existingClaim: media
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads
  metrics:
  # -- Enable and configure prometheus-qbittorrent-exporter sidecar and Prometheus podMonitor.
  # @default -- See values.yaml
    enabled: true
    serviceMonitor:
      interval: 15s
      scrapeTimeout: 5s
      labels: {}
  # -- Enable and configure Prometheus Rules for the chart under this key.
  # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
    # -- Configure additionial rules for the chart under this key.
    # @default -- See prometheusrules.yaml
      rules: []
      # - alert: qBittorrentDown
      #   annotations:
      #     description: qBittorrent service is down.
      #     summary: qBittorrent is down.
      #   expr: |
      #     qbittorrent_up == 0
      #   for: 5m
      #   labels:
      #     severity: critical
    exporter:
      image:
        # -- image repository
        repository: esanchezm/prometheus-qbittorrent-exporter
        # -- image tag
        tag: v1.2.0
        # -- image pull policy
        pullPolicy: IfNotPresent
      env:
        # -- qbittorrent username
        # update value after configuring qbittorrent
        user: "admin"
        # -- qbittorrent password
        # update value after configuring qbittorrent
        password: "adminadmin"
        # -- metrics port
        port: 9022
        # -- log level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
        logLevel: INFO