qbittorrent:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8080
          nodePort: 30001
          targetPort: 8080
    bittorrent:
      enabled: false
      type: ClusterIP
      ports:
        bittorrent:
          enabled: true
          port: 6881
          protocol: TCP
          targetPort: 6881
  persistence:
    media:
      enabled: true
       mountPath: /media
       type: pvc
       existingClaim: media
    downloads:
      enabled: true
       mountPath: /downloads
       type: pvc
       existingClaim: downloads