service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080
        nodePort: 30004
        targetPort: 8080
  bittorrent:
    enabled: false
    type: ClusterIP
    ports:
      bittorrent:
        enabled: true
        port: 6881
        protocol: TCP
        targetPort: 6881