qbittorrent:
  ingress:
    main:
      enabled: true
      hosts:
        - host: test.local
          paths:
            - path: /qbittorrent
              pathType: Prefix
      ingressClassName: nginx
  persistence:
    media:
      enabled: true
      type: pvc
      mountPath: /media
      existingClaim: media
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads