mosquitto:
  service:
    main:
      type: NodePort
      ports:
        http:
          enabled: false
        mqtt:
          enabled: true
          port: 1883
          targetPort: 1883
          nodePort: 31883
  persistence:
    data:
      enabled: true
      mountPath: /mosquitto/data
      accessMode: ReadWriteOnce
      size: 2Gi
    configinc:
      enabled: true
      mountPath: /mosquitto/configinc
      accessMode: ReadWriteOnce
      size: 1Gi