apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lifevisor-syncthing
  name: lifevisor-syncthing-22000
spec:
  ports:
    - name: "22000"
      port: 22000
      targetPort: 22000
    - name: 22000-udp
      port: 22000
      protocol: UDP
      targetPort: 22000
  selector:
    io.kompose.service: lifevisor-syncthing
