apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lifevisor-syncthing
  name: lifevisor-syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lifevisor-syncthing
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: lifevisor-syncthing
    spec:
      containers:
        - image: linuxserver/syncthing:latest
          name: lifevisor-syncthing
          ports:
            - containerPort: 8384
              protocol: TCP
            - containerPort: 22000
              protocol: TCP
            - containerPort: 22000
              protocol: UDP
            - containerPort: 21027
              protocol: UDP
          volumeMounts:
            - mountPath: /mobile-activity-db
              name: mobile-activity-data
              readOnly: true
            - mountPath: /desktop-activity-db
              name: desktop-activity-data
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mobile-activity-data
          persistentVolumeClaim:
            claimName: mobile-activity-data
            readOnly: true
        - name: desktop-activity-data
          persistentVolumeClaim:
            claimName: desktop-activity-data
            readOnly: true
