apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lifevisor-metabase
  name: lifevisor-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lifevisor-metabase
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: lifevisor-metabase
    spec:
      containers:
        - env:
            - name: MB_DB_DBNAME
              value: metabaseappdb
            - name: MB_DB_HOST
              value: lifevisor-postgres
            - name: MB_DB_PASS
              value: mysecretpassword
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_USER
              value: metabase
          image: metabase/metabase:latest
          livenessProbe:
            exec:
              command:
                - curl --fail -I http://localhost:3000/api/health || exit 1
            failureThreshold: 5
            periodSeconds: 15
            timeoutSeconds: 5
          name: metabase
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /mobile-activity-db
              name: mobile-activity-data
              readOnly: true
            - mountPath: /desktop-activity-db
              name: desktop-activity-data
              readOnly: true
      hostname: metabase
      restartPolicy: Always
      volumes:
        - name: mobile-activity-data
          persistentVolumeClaim:
            claimName: mobile-activity-data
            readOnly: true
        - name: desktop-activity-data
          persistentVolumeClaim:
            claimName: desktop-activity-data
            readOnly: true
