apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mobile-activity-data
  name: mobile-activity-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
