ghost:
  ghostUsername: azaurus
  ghostEmail: azaurus@azaurus.dev
  service:
    type: ClusterIP
  ghostHost: "blog.azaurus.dev"
  persistence:
    enabled: true
    type: pvc
    existingClaim: ghost-content