ghost:
  main:
    ports:
      http:
        port: 2368
  persistence:
    content:
      enabled: true
      mountPath: /var/lib/ghost/content
      type: pvc
      existingClaim: ghost-content
  mariadb:
    enabled: false
    architecture: standalone
    auth:
      database: ghost
      username: ghost
      password: ghost
      rootPassword: ghost-rootpass
    primary:
      persistance:
        enabled: false