prometheus:
  service:
    enabled: true
    type: ClusterIP
    servicePort: 80
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: sonarr
          static_configs:
            - targets:
              - sonarr-metrics.default.svc.cluster.local:9794
        - job_name: radarr
          static_configs:
            - targets:
              - radarr-metrics.default.svc.cluster.local:9793
        - job_name: speedtest-exporter
          static_configs:
            - targets:
              - speedtest-exporter.default.svc.cluster.local:9798
                    