prometheus:
  service:
    enabled: true
    type: ClusterIP
    servicePort: 80
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  extraScrapeConfigs: |
    - job_name: 'sonarr'
      metrics_path: /metrics
      static_configs:
        - targets:
          - http://sonarr-metrics.default.svc.cluster.local:9794