prometheus:
  service:
    enabled: true
    type: ClusterIP
    servicePort: 80
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  extraScrapeConfigs:
    - job_name: 'prometheus-blackbox-exporter'
      metrics_path: /probe
      static_configs:
        - targets:
          - https://example.com