prometheus:
  service:
    enabled: true
    type: ClusterIP
    servicePort: 80
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - http://sonarr-metrics.default.svc.cluster.local:9794