spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/azaurus1/homelab
    targetRevision: HEAD
stacks:
  - name: apps
  - name: system
  - name: secrets
  - name: access
  - name: monitoring