matrix-synapse:
  serverName: 'azaurus.dev'
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8008
          nodePort: 30009
          targetPort: 8008
  signingkey:
    existingSecret: matrix-secret-signing-key
    job:
      enabled: false
      
