matrix-synapse:
  serverName: 'azaurus.dev'
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8008
          nodePort: 30009
          targetPort: 8008
  signingkey:
    existingSecret: matrix-secret-signing-key
    job:
      enabled: false

  postgresql:
    enabled: true
    existingSecret: postgresql-secret
    postgresqlUsername: synapse
    postgresqlDatabase: synapse
    postgresqlInitdbArgs: "--lc-collate=C --lc-ctype=C"
    persistence:
      size: 16Gi
      type: pvc
      storageClassName: volume-hostpath
