matrix-synapse:
  serverName: 'azaurus.dev'
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8008
          nodePort: 30009
          targetPort: 8008
  signingkey:
  ## Enable a Kubernetes job to generate and store a signing key if one does not
  ## exist.
  ## If you have already run a Matrix server at some point on your domain then
  ## you will want to keep the old signing key, either by using the `existingSecret`
  ## configuration, or by including the old key under `extraConfig.old_signing_keys`
  ##
  ## If you lose your signing key then any federation traffic from your instance
  ## might not be trusted any more by the wider network.
  ##
  job:
    enabled: true

    generateImage:
      repository: matrixdotorg/synapse
      #tag: latest
      pullPolicy: IfNotPresent

    publishImage:
      repository: bitnami/kubectl
      # tag: latest
      pullPolicy: IfNotPresent
