matrix-synapse:
  serverName: 'azaurus.dev'
  config:
    publicBaseurl: https://matrix.azaurus.dev
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8008
          nodePort: 30009
          targetPort: 8008
  signingkey:
    existingSecret: matrix-secret-signing-key
    job:
      enabled: false
  
  persistence:
    enabled: true
    existingClaim: matrix-synapse-data

  postgresql:
    enabled: true
    existingSecret: postgresql-secret
    postgresqlUsername: synapse
    postgresqlDatabase: synapse
    postgresqlInitdbArgs: "--lc-collate=C --lc-ctype=C"
    persistence:
      existingClaim: matrix-postgresql
  
  redis:
    enabled: true
    auth:
      enabled: true
      existingSecret: redis-secret

