nzbget:
  service:
    main:
      ports:
        http:
          port: 6789
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 2Gi
    media:
      enabled: true
      type: pvc
      mountPath: /media
      existingClaim: media
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads