snipe-it:
  image:
    pullPolicy: IfNotPresent
    repository: snipe/snipe-it
    tag: v6.2.3@sha256:f95f136b8f805626736371283059d6a14f662a533fbba5396458bda5f443f6fd
  mariadb:
    enabled: true
    mariadbDatabase: snipe-it
    mariadbUsername: snipe-it
  persistence:
    backups:
      enabled: true
      mountPath: /var/lib/snipeit/dumps
    data:
      enabled: true
      mountPath: /var/lib/snipeit/data
    logs:
      enabled: true
      mountPath: /var/www/html/storage/logs
  portal:
    open:
      enabled: true
  redis:
    enabled: true
    existingSecret: rediscreds
  securityContext:
    container:
      readOnlyRootFilesystem: false
      runAsGroup: 1000

      runAsUser: 0
    pod:
      fsGroup: 50
  service:
    main:
      ports:
        main:
          port: 10120
          targetPort: 80

