apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corteza-pg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corteza-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corteza-pg
  template:
    metadata:
      labels:
        app: corteza-pg
    spec:
      containers:
        - name: corteza-pg
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "corteza"
            - name: POSTGRES_USER
              value: "corteza"
            - name: POSTGRES_PASSWORD
              value: "corteza-password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: corteza-pg-storage
      volumes:
        - name: corteza-pg-storage
          persistentVolumeClaim:
            claimName: corteza-pg-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: corteza-pg
spec:
  ports:
    - port: 5432
  selector:
    app: corteza-pg
