apiVersion: v1
kind: ConfigMap
metadata:
  name: corteza-config
data:
  DB_DSN: "postgres://corteza:corteza-password@postgres:5432/corteza?sslmode=disable"
  AUTH_SECRET: "your-auth-secret"
  JWT_SECRET: "your-jwt-secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corteza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corteza
  template:
    metadata:
      labels:
        app: corteza
    spec:
      containers:
        - name: corteza
          image: cortezaproject/corteza-server:latest
          envFrom:
            - configMapRef:
                name: corteza-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: corteza
spec:
  ports:
    - port: 80
  selector:
    app: corteza
