apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    logDirectory: /var/log/cloudflared
    tunnel: {{ .Values.tunnelID }}
    credentials-file: .cloudflared/{{.Values.tunnelID}}.json
    warp-routing:
      enabled: {{ .Values.warpRouting }}
    ingress: {{ toYaml .Values.ingress | nindent 6 }}
