apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twentycrm-docker-data-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
