apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twentycrm-db-pvc
spec:
  storageClassName: default
  volumeName: twentycrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
