apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: twenty-server-local-data
  name: twenty-server-local-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
