apiVersion: v1
kind: Secret
metadata:
  name: tokens
type: Opaque
data:
  accessToken: Y2hhbmdlbWU= # Base64 encoded value of "changeme"
  loginToken: Y2hhbmdlbWU= # Base64 encoded value of "changeme"
  refreshToken: Y2hhbmdlbWU= # Base64 encoded value of "changeme"
  fileToken: Y2hhbmdlbWU= # Base64 encoded value of "changeme"
