heimdall:
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 80
          targetPort: 80
          nodePort: 30004
  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: heimdall-config