calibre:
  service:
    main:
      ports:
        main:
          port: 8084
          targetPort: 8080
    webserver:
      enabled: true
      ports:
        webserver:
          enabled: true
          port: 8081
          targetPort: 8081

  persistence:
    config:
      enabled: true
      mountPath: "/config"
    varrun:
      enabled: true
    db:
      enabled: true
      mountPath: /db
      type: pvc
      existingClaim: calibre-db

  portal:
    enabled: true
