---

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- This is the default, you can also use requarks/wiki
image:
  # -- image repository
  repository: linuxserver/calibre
  # -- image tag
  tag: version-v5.21.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-calibre#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Specify the user ID the application will run as
  PUID: "1001"
  # -- Specify the group ID the application will run as
  PGID: "1001"
  # -- Username for the calibre gui
  GUAC_USER:
  # -- Password's md5 hash for the calibre gui
  GUAC_PASS:
  # -- for umask setting of Calibre, default if left unset is 022.
  UMASK_SET: "022"
  # -- Optionally pass cli start arguments to calibre.
  CLI_ARGS:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080
  webserver:
    enabled: false
    type: ClusterIP
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: TCP
        targetPort: 8081

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    # -- Set the ingressClass that is used for this ingress.
    # Requires Kubernetes >=1.19
    ingressClassName: "nginx"

    ## Configure the hosts for the ingress
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: calibre.azaurus.dev
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name:
              # -- Overrides the service port reference for this path
              port:

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi
  books:
    enable: true
    mountPath: /books
    existingClaim: books

