lazylibrarian:
  service:
    main:
      ports:
        http:
          port: 5299
  persistence:
    books:
       enabled: true
       mountPath: /books
       type: pvc
       existingClaim: books
    downloads:
       enabled: true
       mountPath: /downloads
       type: pvc
       existingClaim: downloads
    config:
       enabled: true
    alternate-folder:
      enabled: true
      mountPath: /alternate-import
      type: pvc
      existingClaim: alternate-books-import