ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
  resource.customizations: |
    extensions/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs