ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    data:
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs