apiVersion: v2
name: poste
version: 0.0.0
dependencies:
  - name: common
    version: 17.2.21
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []